version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:20.04-5.7
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.7-focal"

  test:
    image: swift-nio-ssh:20.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:20.04-5.7
