version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"

  test:
    image: swift-nio-ssh:20.04-main
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:20.04-main
