version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:18.04-5.2
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.2"

  test:
    image: swift-nio-ssh:18.04-5.2
    environment:
      #- SANITIZER_ARG=--sanitize=thread
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:18.04-5.2
