version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:16.04-5.1
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.1"

  test:
    image: swift-nio-ssh:16.04-5.1
    environment:
      - SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-warnings-as-errors

  shell:
    image: swift-nio-ssh:16.04-5.1
