version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"

  test:
    image: swift-nio-ssh:20.04-5.5
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:20.04-5.5
