version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:18.04-5.3
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.3-bionic"

  test:
    image: swift-nio-ssh:18.04-5.3
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:18.04-5.3
