version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"

  test:
    image: swift-nio-ssh:22.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:22.04-5.7
