//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// AESGCMTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension AESGCMTests {

   static var allTests : [(String, (AESGCMTests) -> () throws -> Void)] {
      return [
                ("testSimpleAES128RoundTrip", testSimpleAES128RoundTrip),
                ("testSimpleAES256RoundTrip", testSimpleAES256RoundTrip),
                ("testCannotCreateWithIncorrectKeySize", testCannotCreateWithIncorrectKeySize),
                ("testCannotUpdateWithIncorrectKeySize", testCannotUpdateWithIncorrectKeySize),
                ("testCannotCreateWithIncorrectNonceSize", testCannotCreateWithIncorrectNonceSize),
                ("testCannotUpdateWithIncorrectNonceSize", testCannotUpdateWithIncorrectNonceSize),
                ("testDecryptingInvalidCiphertextLengthsAES128", testDecryptingInvalidCiphertextLengthsAES128),
                ("testDecryptingInvalidCiphertextLengthsAES256", testDecryptingInvalidCiphertextLengthsAES256),
                ("testExcessPaddingAES128", testExcessPaddingAES128),
                ("testExcessPaddingAES256", testExcessPaddingAES256),
                ("testInsufficientPaddingAES128", testInsufficientPaddingAES128),
                ("testInsufficientPaddingAES256", testInsufficientPaddingAES256),
                ("testBasicNonceManagement", testBasicNonceManagement),
           ]
   }
}

