//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// HostKeyTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension HostKeyTests {

   static var allTests : [(String, (HostKeyTests) -> () throws -> Void)] {
      return [
                ("testBasicEd25519SigningFlow", testBasicEd25519SigningFlow),
                ("testBasicECDSAP256SigningFlow", testBasicECDSAP256SigningFlow),
                ("testEd25519FailsVerificationWithDifferentKeys", testEd25519FailsVerificationWithDifferentKeys),
                ("testECDASP256FailsVerificationWithDifferentKeys", testECDASP256FailsVerificationWithDifferentKeys),
                ("testEd25519FailsVerificationWithWrongAlgorithms", testEd25519FailsVerificationWithWrongAlgorithms),
                ("testECDASP256FailsVerificationWithWrongAlgorithms", testECDASP256FailsVerificationWithWrongAlgorithms),
                ("testUnrecognisedKey", testUnrecognisedKey),
                ("testInvalidDomainParametersForECDSAP256", testInvalidDomainParametersForECDSAP256),
                ("testUnrecognisedSignature", testUnrecognisedSignature),
           ]
   }
}

