//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SSHMessagesTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SSHMessagesTests {

   static var allTests : [(String, (SSHMessagesTests) -> () throws -> Void)] {
      return [
                ("testDisconnnect", testDisconnnect),
                ("testIgnore", testIgnore),
                ("testUnimplemented", testUnimplemented),
                ("testServiceRequest", testServiceRequest),
                ("testServiceAccept", testServiceAccept),
                ("testKeyExchangeMessage", testKeyExchangeMessage),
                ("testKeyExchangeInit", testKeyExchangeInit),
                ("testKeyExchangeReply", testKeyExchangeReply),
                ("testNewKeys", testNewKeys),
                ("testUserAuthRequest", testUserAuthRequest),
                ("testUserAuthFailure", testUserAuthFailure),
                ("testUserAuthSuccess", testUserAuthSuccess),
                ("testGlobalRequest", testGlobalRequest),
                ("testChannelOpen", testChannelOpen),
                ("testChannelOpenConfirmation", testChannelOpenConfirmation),
                ("testChannelOpenFailure", testChannelOpenFailure),
                ("testChannelWindowAdjust", testChannelWindowAdjust),
                ("testChannelData", testChannelData),
                ("testChannelExtendedData", testChannelExtendedData),
                ("testChannelEOF", testChannelEOF),
                ("testChannelClose", testChannelClose),
                ("testChannelRequest", testChannelRequest),
                ("testChannelSuccess", testChannelSuccess),
                ("testChannelFailure", testChannelFailure),
                ("testTypeError", testTypeError),
                ("testRequestSuccess", testRequestSuccess),
                ("testRequestFailure", testRequestFailure),
           ]
   }
}

